[2025-08-27 17:21:19,626] 293 langchain_core.callbacks.manager - WARNING - Error in StdOutCallbackHandler.on_chain_start callback: AttributeError("'NoneType' object has no attribute 'get'")
[2025-08-27 17:21:19,627] 293 langchain_core.callbacks.manager - WARNING - Error in StdOutCallbackHandler.on_chain_start callback: AttributeError("'NoneType' object has no attribute 'get'")
[2025-08-27 17:21:23,583] 1025 httpx - INFO - HTTP Request: POST https://api.together.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2025-08-27 17:21:23,619] 293 langchain_core.callbacks.manager - WARNING - Error in StdOutCallbackHandler.on_chain_start callback: AttributeError("'NoneType' object has no attribute 'get'")
[2025-08-27 17:21:27,686] 1025 httpx - INFO - HTTP Request: POST https://api.together.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2025-08-27 17:22:19,651] 293 langchain_core.callbacks.manager - WARNING - Error in StdOutCallbackHandler.on_chain_start callback: AttributeError("'NoneType' object has no attribute 'get'")
[2025-08-27 17:22:19,652] 293 langchain_core.callbacks.manager - WARNING - Error in StdOutCallbackHandler.on_chain_start callback: AttributeError("'NoneType' object has no attribute 'get'")
[2025-08-27 17:22:23,547] 1025 httpx - INFO - HTTP Request: POST https://api.together.ai/v1/chat/completions "HTTP/1.1 200 OK"
[2025-08-27 17:22:23,553] 293 langchain_core.callbacks.manager - WARNING - Error in StdOutCallbackHandler.on_chain_start callback: AttributeError("'NoneType' object has no attribute 'get'")
[2025-08-27 17:22:28,086] 1025 httpx - INFO - HTTP Request: POST https://api.together.ai/v1/chat/completions "HTTP/1.1 200 OK"
